version: '3.8'

services:
  svelte-kit:
    container_name: svelte-kit-dev
    dockerfile: Dockerfile.dev
    restart: always
    build:
      context: ./docker/js/adapter-node
    volumes:
      - ./docker/js/adapter-node/:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 24678:24678
